name: taskrouter

on:
  issues:
    types: [labeled]

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Run Task Router Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          LABEL_NAME: ${{ github.event.label.name }}
        run: bash <(curl -s https://raw.githubusercontent.com/neuralmesh/apimesh/main/taskrouter.sh)

